### ISSUE TITLE
Resolve UseEffect & setAnnotations bug

### ISSUE THREAD

**Issue by SamReeve96** [SamReeve96/Acetate#36]
When an annotation is deleted or modified in the react state, the content script sheet object doesn't seem to be updated via useEffect, for now, the sheet is kept in sync by calling the sync method when deleting or modifying annotations.

**Comment by Kuboczoch** [comment]
@SamReeve96 You are missing dependencies in your useEffect, correct structure:
```
useEffect(() => {
...
}, [yourDependencies])
```

So if you are using your useEffect like this:
```
React.useEffect(() => {
        document.title = document.title + ` : (Acetate Active) - ${annotations.length} annotations`
})
```
Then try to use it that way:
```
React.useEffect(() => {
        document.title = document.title + ` : (Acetate Active) - ${annotations.length} annotations`
}, [document.title, annotations])
```
In this example, your useEffect will execute itself when at least one of its dependencies changed. I'm not familiar with your entire code structure, but if `annotations` is always an array then you can try annotations.length to minimize re-rendering.

**Comment by SamReeve96** [comment]
> @SamReeve96 You are missing dependencies in your useEffect, correct structure:
> 
> ```
> useEffect(() => {
> ...
> }, [yourDependencies])
> ```
> 
> So if you are using your useEffect like this:
> 
> ```
> React.useEffect(() => {
>         document.title = document.title + ` : (Acetate Active) - ${annotations.length} annotations`
> })
> ```
> 
> Then try to use it that way:
> 
> ```
> React.useEffect(() => {
>         document.title = document.title + ` : (Acetate Active) - ${annotations.length} annotations`
> }, [document.title, annotations])
> ```
> 
> In this example, your useEffect will execute itself when at least one of its dependencies changed. I'm not familiar with your entire code structure, but if `annotations` is always an array then you can try annotations.length to minimize re-rendering.

Thanks! @Kuboczoch This was giving me a bit of a headache, so I really appreciate the explanation.
